CREATE SCHEMA public;

CREATE TABLE public.MESTO (
    IdMes INTEGER NOT NULL,
    Naziv VARCHAR(20) NULL,
    PRIMARY KEY (IdMes)
);

CREATE TABLE public.POL (
    IdPol INTEGER NOT NULL,
    Naziv VARCHAR(1) NULL,
    PRIMARY KEY (IdPol)
);

CREATE TABLE public.UZRAST (
    IdUzr INTEGER NOT NULL,
    Uzrast INTEGER NOT NULL,
    PRIMARY KEY (IdUzr)
);

CREATE TABLE public.VIDEO (
    IdVid INTEGER NOT NULL,
    NazivVideo VARCHAR(20) NULL,
    NazivKategorija VARCHAR(20) NULL,
    PRIMARY KEY (IdVid)
);

CREATE TABLE public.VREME (
    IdVre INTEGER NOT NULL,
    Vreme TIME NOT NULL,
    PRIMARY KEY (IdVre)
);

CREATE TABLE public.GLEDANJA (
    BrMinuta INTEGER NULL,
    IdVre INTEGER NOT NULL,
    IdVid INTEGER NOT NULL,
    IdPol INTEGER NOT NULL,
    IdUzr INTEGER NOT NULL,
    IdMesGle INTEGER NOT NULL,
    IdMesVla INTEGER NOT NULL,
    PRIMARY KEY (IdVre, IdVid, IdPol, IdUzr, IdMesGle, IdMesVla),
    FOREIGN KEY (IdVre) REFERENCES public.VREME(IdVre) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdVid) REFERENCES public.VIDEO(IdVid) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdPol) REFERENCES public.POL(IdPol) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdUzr) REFERENCES public.UZRAST(IdUzr) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdMesGle) REFERENCES public.MESTO(IdMes) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdMesVla) REFERENCES public.MESTO(IdMes) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE public.OCENE (
    IdVre INTEGER NOT NULL,
    IdVid INTEGER NOT NULL,
    IdPol INTEGER NOT NULL,
    IdMesGle INTEGER NOT NULL,
    IdMesVla INTEGER NOT NULL,
    Ocena INTEGER NULL,
    IdUzr INTEGER NOT NULL,
    PRIMARY KEY (IdVre, IdVid, IdPol, IdMesGle, IdMesVla, IdUzr),
    FOREIGN KEY (IdVre) REFERENCES public.VREME(IdVre) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdVid) REFERENCES public.VIDEO(IdVid) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdPol) REFERENCES public.POL(IdPol) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdUzr) REFERENCES public.UZRAST(IdUzr) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdMesGle) REFERENCES public.MESTO(IdMes) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdMesVla) REFERENCES public.MESTO(IdMes) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE public.PRETPLATE (
    IdVre INTEGER NOT NULL,
    IdPol INTEGER NOT NULL,
    IdUzr INTEGER NOT NULL,
    IdMes INTEGER NOT NULL,
    Cena FLOAT NOT NULL,
    PRIMARY KEY (IdVre, IdPol, IdUzr, IdMes),
    FOREIGN KEY (IdVre) REFERENCES public.VREME(IdVre) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdPol) REFERENCES public.POL(IdPol) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdUzr) REFERENCES public.UZRAST(IdUzr) ON DELETE NO ACTION ON UPDATE NO ACTION,
    FOREIGN KEY (IdMes) REFERENCES public.MESTO(IdMes) ON DELETE NO ACTION ON UPDATE NO ACTION
);
